# Generated by Django 3.0.2 on 2022-06-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('board_name', models.CharField(default='notice', max_length=50, verbose_name='게시판 이름')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('delYn', models.PositiveIntegerField(default=0, verbose_name='삭제여부')),
            ],
        ),
    ]
